[package]
org = "ayesh"
name = "data_ingestion_svc"
version = "0.1.0"
distribution = "2201.13.1"

[build-options]
observabilityIncluded = true

[[tool.consolidate-packages]]
id = "consolidatePackages1"
options.services = ["ayesh/data_ingestion"]
