[package]
org = "ayesh"
name = "kafka_consumer_svc"
version = "0.1.0"
distribution = "2201.13.1"

[build-options]
observabilityIncluded = true

[[tool.consolidate-packages]]
id = "consolidatePackages1"
options.services = ["ayesh/cache_enricher","ayesh/stream_processor"]
